name: Shive_work_flow
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
env:
    # Add environment variable for MongoDB connection
    MONGODB_URI: ${{ secrets.MONGODB_URI }}
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        services:
            mongo:
                image: mongo:latest
                ports:
                    - 27017:27017
        steps:
            - name: Checkout to build
              uses: actions/checkout@v2
            - name: Install go and run linting
              id: Install-go
              uses: reviewdog/action-golangci-lint@v2
            - name: Get dependencies to Build
              id: Get-dependencies-to-Build
              run: |
                  go get -v -t -d ./...
                  if [ -f Gopkg.toml ]; then
                      curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                      dep ensure
                  fi

            - name: Create .env file
              run: |
                  echo "PORT=9000" >> .env
                  echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
                  echo "ENV=production" >> .env

            - name: Build Code
              id: Build-Code
              run: |
                  go build -o shive-app -v .

            - name: Start API Server
              env:
                  # Add any environment variables your app needs
                  PORT: "9000"
                  ENV: "production"
                  # MongoDB URI is already set at the workflow level
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
              run: |
                  ./shive-app &
                  sleep 20
            - name: Run  auth tests
              env:
                  API_URL: http://localhost:9000
              run: go test -v ./test/auth_test.go

            # Added jq installation since the shell script uses it to parse JSON
            # - name: Install jq
            #   run: sudo apt-get install -y jq

            # # Make the test script executable and run it
            # - name: Make API test script executable
            #   run: chmod +x api-test.shell

            # - name: Run API tests
            #   run: ./api-test.shell
